name: dungeon_paper
description: A Dungeon World character sheet app written with Flutter.
version: 1.2.6+75

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  apple_sign_in: ^0.1.0
  cached_network_image: ^2.5.0
  cloud_firestore: ^0.14.4
  cupertino_icons: ^1.0.0
  dungeon_world_data: ^2.0.5+9
  email_validator: ^1.0.5
  excel: ^1.1.5
  facebook_app_events: ^0.8.2
  firebase_analytics: ^6.3.0
  firebase_auth: ^0.18.4+1
  firebase_core: ^0.5.3
  firebase_crashlytics: ^0.2.4
  firebase_storage: ^5.2.0
  flutter_file_dialog: ^0.0.5
  flutter_image: ^3.0.0
  flutter_markdown: ^0.5.2
  flutter_redux: ^0.6.0
  flutter_staggered_grid_view: ^0.3.2
  flutter_svg: ^0.19.0
  flutter_typeahead: ^1.8.8
  freezed_annotation: ^0.12.0
  get: ^3.24.0
  git_hooks: ^0.0.4
  google_sign_in: ^4.4.4
  http: ^0.12.2
  icon_shadow: ^1.0.1
  image_picker: ^0.6.7+17
  logger: ^0.9.4
  package_info_plus: ^0.6.3
  path: ^1.7.0
  path_provider: ^1.6.18
  platform: ^2.2.1
  pub_semver: ^1.4.4
  quiver_hashcode: ^2.0.0
  redux_logging: ^0.4.0
  screen: ^0.0.5
  share: ^0.6.5+2
  shared_preferences: ^0.5.12
  universal_html: ^1.2.3
  url_launcher: ^5.7.2
  uuid: ^2.2.2
  wheel_spinner: ^0.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  args: ^1.5.2
  build_runner: ^1.10.13
  flutter_launcher_icons: ^0.7.5
  freezed: ^0.12.7
  json_serializable: ^3.5.1
  pedantic: ^1.9.2

flutter_icons:
  android: true
  ios: true
  image_path_android: launcher_icons/android.png
  image_path_ios: launcher_icons/ios.png

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - secrets.json
    - assets/logo.png

    # dice
    - assets/dice/d4.svg
    - assets/dice/d6.svg
    - assets/dice/d8.svg
    - assets/dice/d10.svg
    - assets/dice/d12.svg
    - assets/dice/d20.svg

    # social
    - assets/social/discord.svg
    - assets/social/facebook.svg
    - assets/social/github.svg
    - assets/social/twitter.svg
    - assets/social/google.svg
    - assets/social/google.png
    - assets/social/apple.svg

    - assets/armor.svg
    - assets/bag.svg
    - assets/book-stack.svg
    - assets/coin-stack.svg
    - assets/dumbbell.svg
    - assets/swords.svg
    # - assets/quill.svg
    # - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  fonts:
    # - family: "Noto Sans"
    #   fonts:
    #     - asset: assets/fonts/Noto_Sans_KR/NotoSansKR-Black.otf
    #       weight: 900
    #     - asset: assets/fonts/Noto_Sans_KR/NotoSansKR-Bold.otf
    #       weight: 700
    #     - asset: assets/fonts/Noto_Sans_KR/NotoSansKR-Medium.otf
    #       weight: 500
    #     - asset: assets/fonts/Noto_Sans_KR/NotoSansKR-Regular.otf
    #       weight: 400
    #     - asset: assets/fonts/Noto_Sans_KR/NotoSansKR-Light.otf
    #       weight: 300
    #     - asset: assets/fonts/Noto_Sans_KR/NotoSansKR-Thin.otf
    #       weight: 100
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-Black.ttf
          weight: 900
        - asset: assets/fonts/Nunito/Nunito-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Nunito/Nunito-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Nunito/Nunito-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Nunito/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito/Nunito-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Nunito/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito/Nunito-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Nunito/Nunito-Regular.ttf
          weight: 400
        # - asset: assets/fonts/Nunito/Nunito-RegularItalic.ttf
        #   weight: 400
        #   style: italic
        - asset: assets/fonts/Nunito/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito/Nunito-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Nunito/Nunito-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Nunito/Nunito-ExtraLightItalic.ttf
          weight: 200
          style: italic
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
