name: dungeon_paper
description: A Dungeon World character sheet app written with Flutter.

dependencies:
  flutter:
    sdk: flutter
  wheel_spinner: ^0.0.6
  # wheel_spinner:
  #   path: ../wheel_spinner
  dungeon_world_data: ^2.0.5+6
  # dungeon_world_data:
  #   path: ../dw_data
  # Firebase/Firestore
  firebase_core: ^0.4.4+3
  firebase_auth: ^0.16.0
  firebase_crashlytics: ^0.1.3+3
  firebase_analytics: ^5.0.11
  cloud_firestore: ^0.13.5
  google_sign_in: ^4.4.4
  # Web Deps
  # firebase_core_web: ^0.1.1+2
  # google_sign_in_web: ^0.9.1
  #
  shared_preferences: ^0.5.6
  screen: ^0.0.4
  cupertino_icons: ^0.1.2
  flutter_redux: ^0.6.0
  flutter_staggered_grid_view: ^0.3.0
  flutter_markdown: ^0.2.0
  url_launcher: ^5.4.5
  redux_logging: ^0.4.0
  flutter_svg: ^0.18.0
  # quiver: '>=2.0.0 <3.0.0'
  flutter_image: ^3.0.0
  uuid: ^2.0.0
  # sentry: ^2.2.0
  package_info: ^0.4.0+6
  quiver_hashcode: ^2.0.0
  http: ^0.12.0+4
  pub_semver: ^1.4.2
  flutter_typeahead: ^1.7.0
  pedantic: ^1.8.0
  universal_html: ^1.2.2
  reorderables: ^0.3.2
  flutter_file_dialog: ^0.0.5
  path_provider: ^1.6.11
  path: ^1.7.0
  # permission_handler: ^5.0.1+1
  logger: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.0

flutter_icons:
  image_path: launcher_icons/android.png
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - secrets.json
    - assets/logo.png

    # dice
    - assets/dice/d4.svg
    - assets/dice/d6.svg
    - assets/dice/d8.svg
    - assets/dice/d10.svg
    - assets/dice/d12.svg
    - assets/dice/d20.svg

    # social
    - assets/social/discord.svg
    - assets/social/facebook.svg
    - assets/social/github.svg
    - assets/social/twitter.svg

    - assets/armor.svg
    - assets/bag.svg
    - assets/book-stack.svg
    - assets/coin-stack.svg
    - assets/dumbbell.svg
    - assets/swords.svg
    # - assets/quill.svg
    # - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
