name: dungeon_paper
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  wheel_spinner: ^0.0.6
  # wheel_spinner:
  #   path: ../wheel_spinner
  # Firebase/Firestore
  firebase_core: ^0.3.1+1
  firebase_auth: ^0.8.1+4
  cloud_firestore: ^0.9.5+2
  #
  screen: ^0.0.4
  cupertino_icons: ^0.1.2
  google_sign_in: ^4.0.1+1
  flutter_redux: ^0.5.3
  shared_preferences: ^0.5.0
  flutter_staggered_grid_view: ^0.3.0
  flutter_markdown: ^0.2.0
  url_launcher: ^5.0.0
  dungeon_world_data: ^1.3.4
  redux_logging: ^0.3.0
  flutter_svg: ^0.13.0+2
  # quiver: '>=2.0.0 <3.0.0'
  flutter_image: ^1.0.0
  uuid: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.0

flutter_icons:
  image_path: launcher_icons/android.png
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/swords.svg
    - assets/dice.svg
    - assets/bag.svg
    - assets/armor.svg
    # - assets/quill.svg
    # - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
