// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhmhBoM81HfITEZdH8yE1M7uFcQpv0lYs',
    appId: '1:168370418374:web:ef411af9348555e3b55dc7',
    messagingSenderId: '168370418374',
    projectId: 'magnus--dungeon-paper',
    authDomain: 'magnus--dungeon-paper.firebaseapp.com',
    storageBucket: 'magnus--dungeon-paper.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7W1eHot3r0QzKZdZOctmw1PNON9SXalU',
    appId: '1:168370418374:android:73f5e62c013e47a8b55dc7',
    messagingSenderId: '168370418374',
    projectId: 'magnus--dungeon-paper',
    storageBucket: 'magnus--dungeon-paper.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBywx73oAat53Oty-RzJK7n3qt6GtBRnds',
    appId: '1:168370418374:ios:40ad73aa84a3230ab55dc7',
    messagingSenderId: '168370418374',
    projectId: 'magnus--dungeon-paper',
    storageBucket: 'magnus--dungeon-paper.appspot.com',
    iosBundleId: 'app.dungeonPaper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBywx73oAat53Oty-RzJK7n3qt6GtBRnds',
    appId: '1:168370418374:ios:40ad73aa84a3230ab55dc7',
    messagingSenderId: '168370418374',
    projectId: 'magnus--dungeon-paper',
    storageBucket: 'magnus--dungeon-paper.appspot.com',
    iosBundleId: 'app.dungeonPaper',
  );
}
