/// Flutter icons DwIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
// ignore_for_file: constant_identifier_names

import 'package:flutter/widgets.dart';

class DwIcons {
  DwIcons._();

  static const _kFontFam = 'DwIcons';
  static const String? _kFontPkg = null;

  static const IconData armor = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData book_cover =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData coin_stack =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dice_d6_numbered =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dumbbell = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exclamation =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hand_rock = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData knapsack = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData quill = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData riposte = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scroll_quill =
      IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData swap_bag = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData swords = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stat_cha = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stat_con = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stat_dex = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stat_int = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stat_str = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stat_wis = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dice_d4 = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dice_d6 = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dice_d8 = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dice_d10 = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dice_d12 = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dice_d20 = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static IconData statIcon(String stat) => {
        'cha': DwIcons.stat_cha,
        'con': DwIcons.stat_con,
        'dex': DwIcons.stat_dex,
        'int': DwIcons.stat_int,
        'str': DwIcons.stat_str,
        'wis': DwIcons.stat_wis,
      }[stat]!;

  static IconData diceIcon(int sides) => {
        4: DwIcons.dice_d4,
        6: DwIcons.dice_d6,
        8: DwIcons.dice_d8,
        10: DwIcons.dice_d10,
        12: DwIcons.dice_d12,
        20: DwIcons.dice_d20,
      }[sides]!;
}
